# Pytorch Introduction


In [2]:
%pip install torch
import torch

Note: you may need to restart the kernel to use updated packages.


In [3]:
torch.__version__

'2.0.1'

In [53]:
scalar = torch.tensor(7)
vector = torch.tensor([1, 2, 3])
M1 = torch.tensor([[1, 2], [3, 4], [4, 5]])
M2 = M1.T    # this only works for 2D tensors
print(f'M2 = {M2} with shape {M2.shape}')
M3 = torch.transpose(M1,0,1)
print(f'M3 = {M3} with shape {M3.shape}')




M2 = tensor([[1, 3, 4],
        [2, 4, 5]]) with shape torch.Size([2, 3])
M3 = tensor([[1, 3, 4],
        [2, 4, 5]]) with shape torch.Size([2, 3])


In [32]:
M3= torch.tensor([[1, 2, 3], [4, 5, 6]])
M4 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
print(f'M3 = {M3} with shape {M3.shape}')
print(f'M4={M4} with shape {M4.shape}')
result = torch.matmul(M3.T,M3)
result

M3 = tensor([[1, 2, 3],
        [4, 5, 6]]) with shape torch.Size([2, 3])
M4=tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[7, 8, 9],
         [0, 1, 2]]]) with shape torch.Size([2, 2, 3])


tensor([[17, 22, 27],
        [22, 29, 36],
        [27, 36, 45]])

# Random Tensors

In [23]:
M1 = torch.rand(3, 3)
M2 = torch.rand(10,10)
T1 = torch.rand(3, 4, 4)
T1

tensor([[[0.5409, 0.8765, 0.4597, 0.9090],
         [0.3296, 0.1171, 0.7557, 0.2811],
         [0.1850, 0.5942, 0.9484, 0.6683],
         [0.5376, 0.4324, 0.3399, 0.1467]],

        [[0.6704, 0.8111, 0.5412, 0.9128],
         [0.0047, 0.4294, 0.6374, 0.7867],
         [0.5108, 0.2214, 0.0272, 0.4520],
         [0.1799, 0.4876, 0.0866, 0.5837]],

        [[0.4769, 0.7019, 0.1148, 0.7994],
         [0.3846, 0.3354, 0.7667, 0.0818],
         [0.4080, 0.6779, 0.0440, 0.0072],
         [0.5776, 0.5763, 0.7583, 0.5151]]])

In [251]:
matrix_ones = torch.ones(5, 5)

# Use torch.triu() to get the upper triangular matrix
triangular_matrix = torch.triu(matrix_ones)

triangular_matrix

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [252]:
# Use torch.tril() to get the lower triangular matrix
triangular_matrix = torch.tril(matrix_ones)
triangular_matrix

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [253]:
# from a full random matrix of 5x5 get the first element of row 1, the first two elements of row 2, the first three elements of row 3, and so on
matrix = torch.rand(5, 5)
print(matrix)
result = matrix * triangular_matrix
result


tensor([[0.0851, 0.0920, 0.2883, 0.1000, 0.1125],
        [0.3914, 0.5415, 0.4734, 0.5778, 0.5243],
        [0.9170, 0.5597, 0.5344, 0.5249, 0.5105],
        [0.4227, 0.4324, 0.9338, 0.4716, 0.8871],
        [0.7086, 0.9835, 0.9304, 0.1313, 0.1451]])


tensor([[0.0851, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3914, 0.5415, 0.0000, 0.0000, 0.0000],
        [0.9170, 0.5597, 0.5344, 0.0000, 0.0000],
        [0.4227, 0.4324, 0.9338, 0.4716, 0.0000],
        [0.7086, 0.9835, 0.9304, 0.1313, 0.1451]])

In [254]:
# create a matrix of ones "like" result, but with the ones on the lower triangular part
# make lower triangle ones by usine torch.like
lower_ones = torch.ones_like(result).tril()
lower_ones







tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [255]:
# matrix multiplication
A = torch.ones(2,3)
M = torch.matmul(A, A.T)
M

tensor([[3., 3.],
        [3., 3.]])

In [256]:
# Squeeze removes all the dimensions that have a size of 1
A = torch.tensor([[1, 2, 3]]).squeeze()
A.shape

torch.Size([3])

In [257]:
# permute the dimensions of a tensor for a color image 10x10x3 with 3 channels
image = torch.rand(10, 10, 3)
print(image.shape)
new_image = image.permute(2, 0, 1)  
new_image.shape

torch.Size([10, 10, 3])


torch.Size([3, 10, 10])

In [258]:
# indexing and slicing
# create a 3x3 matrix with random values
matrix = torch.rand(3, 3)
print(matrix)
# get the first row
first_row = matrix[0, 0:2]
first_row

tensor([[5.1828e-01, 8.6017e-01, 2.3171e-01],
        [2.1220e-01, 9.1323e-01, 6.7700e-01],
        [1.6902e-01, 3.0833e-04, 3.2400e-01]])


tensor([0.5183, 0.8602])

In [259]:
# Get a GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

# Python Classes

In [260]:
# Python Classes https://www.geeksforgeeks.org/python-classes-and-objects/#
class Dog:
    # Class Attribute
    species = 'mammal'
    # Initializer / Instance Attributes
    def __init__(self, name, age):
        self.name = name
        self.age = age
    # instance method
    def description(self):
        return "{} is {} years old".format(self.name, self.age)
    # instance method
    def speak(self, sound):
        return "{} says {}".format(self.name, sound)
    
# Instantiate the Dog object
mikey = Dog("Mikey", 6)
# call our instance methods
print(mikey.description())
print(mikey.speak("Gruff Gruff"))

Mikey is 6 years old
Mikey says Gruff Gruff


# Linear Regression Model

In [261]:
# generate training data for line y = 2x + 3
import numpy as np
import torch
X_train = torch.tensor([[1, 1], [2, 1], [3, 1], [4, 1], [5, 1]], dtype=torch.float32)
y_train = torch.tensor([[5], [7], [9], [11], [13]], dtype=torch.float32)
print(X_train)
print(y_train)

tensor([[1., 1.],
        [2., 1.],
        [3., 1.],
        [4., 1.],
        [5., 1.]])
tensor([[ 5.],
        [ 7.],
        [ 9.],
        [11.],
        [13.]])


In [262]:
# Build the Neural Network
class LinearRegressionNet(nn.Module):
    def __init__(self):
        super(LinearRegressionNet, self).__init__()
        # One fully connected layer (input_dim=2, output_dim=1)
        self.fc = nn.Linear(2, 1)
        
    def forward(self, x):
        return self.fc(x)

# Instantiate the network
net = LinearRegressionNet()

# Define the loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.01)

# Train the Network
num_epochs = 1000
for epoch in range(num_epochs):
    # Zero the gradients
    optimizer.zero_grad()
    
    # Forward pass
    outputs = net(x)
    loss = criterion(outputs, y)
    
    # Backward pass and optimize
    loss.backward()
    optimizer.step()

    # Print loss every 100 epochs
    if (epoch+1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Test the network
test_data = torch.tensor([[6, 1], [7, 1]], dtype=torch.float32)
predictions = net(test_data)
predictions


Epoch [100/1000], Loss: 0.1125
Epoch [200/1000], Loss: 0.0317
Epoch [300/1000], Loss: 0.0090
Epoch [400/1000], Loss: 0.0025
Epoch [500/1000], Loss: 0.0007
Epoch [600/1000], Loss: 0.0002
Epoch [700/1000], Loss: 0.0001
Epoch [800/1000], Loss: 0.0000
Epoch [900/1000], Loss: 0.0000
Epoch [1000/1000], Loss: 0.0000


tensor([[15.0018],
        [17.0025]], grad_fn=<AddmmBackward0>)

# Recode using weights as nn.Parameter