# Pytorch Introduction


In [2]:
%pip install torch
import torch

Note: you may need to restart the kernel to use updated packages.


In [24]:
torch.__version__

'2.0.1'

In [8]:
scalar = torch.tensor(7)
vector = torch.tensor([1, 2, 3])
Matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
T = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [0, 1, 2]]])
T.shape

torch.Size([2, 2, 3])

# Random Tensors

In [17]:
M1 = torch.rand(3, 3)
M2 = torch.rand(10,10)
T1 = torch.rand(3, 4, 4)
T1

tensor([[[0.1539, 0.7869, 0.6750, 0.6658],
         [0.9114, 0.5779, 0.4311, 0.9734],
         [0.4569, 0.1145, 0.2356, 0.8486],
         [0.6986, 0.9804, 0.1676, 0.4860]],

        [[0.4843, 0.4959, 0.8466, 0.7865],
         [0.3530, 0.2643, 0.6462, 0.7399],
         [0.2642, 0.9976, 0.6244, 0.7249],
         [0.8854, 0.4276, 0.9680, 0.4813]],

        [[0.8533, 0.6192, 0.5852, 0.0783],
         [0.7853, 0.4494, 0.1220, 0.8367],
         [0.6685, 0.5135, 0.4729, 0.0401],
         [0.0324, 0.1846, 0.4393, 0.4899]]])

In [18]:
matrix_ones = torch.ones(5, 5)

# Use torch.triu() to get the upper triangular matrix
triangular_matrix = torch.triu(matrix_ones)

triangular_matrix

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
# Use torch.tril() to get the lower triangular matrix
triangular_matrix = torch.tril(matrix_ones)
triangular_matrix

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [29]:
# from a full random matrix of 5x5 get the first element of row 1, the first two elements of row 2, the first three elements of row 3, and so on
matrix = torch.rand(5, 5)
print(matrix)
result = matrix * triangular_matrix
result


tensor([[0.9911, 0.2453, 0.4995, 0.4340, 0.2305],
        [0.0551, 0.4455, 0.7469, 0.4306, 0.0784],
        [0.3532, 0.0839, 0.8456, 0.4183, 0.5111],
        [0.1046, 0.7920, 0.3601, 0.6448, 0.5902],
        [0.2034, 0.1081, 0.9074, 0.0270, 0.2226]])


tensor([[0.9911, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0551, 0.4455, 0.0000, 0.0000, 0.0000],
        [0.3532, 0.0839, 0.8456, 0.0000, 0.0000],
        [0.1046, 0.7920, 0.3601, 0.6448, 0.0000],
        [0.2034, 0.1081, 0.9074, 0.0270, 0.2226]])

In [39]:
# create a matrix of ones "like" result, but with the ones on the lower triangular part
# make lower triangle ones by usine torch.like
lower_ones = torch.ones_like(result).tril()
lower_ones







tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [45]:
# matrix multiplication
A = torch.ones(2,3)
M = torch.matmul(A, A.T)
M

tensor([[3., 3.],
        [3., 3.]])

In [52]:
# Squeeze removes all the dimensions that have a size of 1
A = torch.tensor([[1, 2, 3]]).squeeze()
A.shape

torch.Size([3])

In [55]:
# permute the dimensions of a tensor for a color image 10x10x3 with 3 channels
image = torch.rand(10, 10, 3)
print(image.shape)
new_image = image.permute(2, 0, 1)  
new_image.shape

tensor([[[0.9608, 0.9321, 0.3588],
         [0.5724, 0.6607, 0.5960],
         [0.4027, 0.7418, 0.7644],
         [0.4260, 0.1665, 0.0990],
         [0.3024, 0.1791, 0.1687],
         [0.9642, 0.4929, 0.7166],
         [0.8359, 0.4706, 0.1586],
         [0.0098, 0.1721, 0.3984],
         [0.4349, 0.4465, 0.7395],
         [0.0307, 0.6142, 0.1029]],

        [[0.9400, 0.0477, 0.3782],
         [0.5026, 0.0909, 0.2089],
         [0.8123, 0.3465, 0.4826],
         [0.6505, 0.9197, 0.5523],
         [0.9312, 0.0876, 0.7332],
         [0.1034, 0.2137, 0.7622],
         [0.0426, 0.6859, 0.7046],
         [0.7085, 0.6276, 0.5308],
         [0.5489, 0.7457, 0.6198],
         [0.4037, 0.2814, 0.0224]],

        [[0.4936, 0.3626, 0.9407],
         [0.5455, 0.8841, 0.8323],
         [0.5251, 0.7770, 0.4924],
         [0.1127, 0.2997, 0.3147],
         [0.1739, 0.9770, 0.7629],
         [0.6068, 0.1075, 0.0246],
         [0.4059, 0.0325, 0.8876],
         [0.8786, 0.4393, 0.6985],
         [0.2405

torch.Size([3, 10, 10])